// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHEQA3rYnWLMNs0fwlXONoWletppZ2PA',
    appId: '1:874956743799:web:da0498b8d0ef72a80f9272',
    messagingSenderId: '874956743799',
    projectId: 'expense-tracker-59188',
    authDomain: 'expense-tracker-59188.firebaseapp.com',
    storageBucket: 'expense-tracker-59188.firebasestorage.app',
    measurementId: 'G-Z94CT7C316',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kdZBCY70WKYKCG-GLndjEnbzvxoYbYc',
    appId: '1:874956743799:android:3cd9b8c9cc8859930f9272',
    messagingSenderId: '874956743799',
    projectId: 'expense-tracker-59188',
    storageBucket: 'expense-tracker-59188.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLv1al3tPDKE199ucvIziCJ65eN_VzeXY',
    appId: '1:874956743799:ios:8689a8fd770ca6260f9272',
    messagingSenderId: '874956743799',
    projectId: 'expense-tracker-59188',
    storageBucket: 'expense-tracker-59188.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
